// Code generated by gotestmd DO NOT EDIT.
package k8s_monolith

import (
	"github.com/stretchr/testify/suite"

	"github.com/networkservicemesh/integration-tests/extensions/base"
	"github.com/networkservicemesh/integration-tests/suites/k8s_monolith/external_nsc"
	"github.com/networkservicemesh/integration-tests/suites/k8s_monolith/external_nse"
)

type Suite struct {
	base.Suite
	external_nscSuite external_nsc.Suite
	external_nseSuite external_nse.Suite
}

func (s *Suite) SetupSuite() {
	parents := []interface{}{&s.Suite}
	for _, p := range parents {
		if v, ok := p.(suite.TestingSuite); ok {
			v.SetT(s.T())
		}
		if v, ok := p.(suite.SetupAllSuite); ok {
			v.SetupSuite()
		}
	}
	s.RunIncludedSuites()
}
func (s *Suite) RunIncludedSuites() {
	s.Run("External_nsc", func() {
		suite.Run(s.T(), &s.external_nscSuite)
	})
	s.Run("External_nse", func() {
		suite.Run(s.T(), &s.external_nseSuite)
	})
}
func (s *Suite) Test() {}
