// Code generated by gotestmd DO NOT EDIT.
package loadbalancer

import (
	"github.com/stretchr/testify/suite"

	"github.com/networkservicemesh/integration-tests/extensions/base"
)

type Suite struct {
	base.Suite
}

func (s *Suite) SetupSuite() {
	parents := []interface{}{&s.Suite}
	for _, p := range parents {
		if v, ok := p.(suite.TestingSuite); ok {
			v.SetT(s.T())
		}
		if v, ok := p.(suite.SetupAllSuite); ok {
			v.SetupSuite()
		}
	}
	r := s.Runner("../deployments-k8s/examples/k8s_monolith/configuration/loadbalancer")
	s.T().Cleanup(func() {
		r.Run(`if [[ ! -z $CLUSTER_CIDR ]]; then` + "\n" + `  kubectl delete ns metallb-system` + "\n" + `fi`)
	})
	r.Run(`if [[ ! -z $CLUSTER_CIDR ]]; then` + "\n" + `  kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/namespace.yaml` + "\n" + `  kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"` + "\n" + `  kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/metallb.yaml` + "\n" + `  cat > metallb-config.yaml <<EOF` + "\n" + `  apiVersion: v1` + "\n" + `  kind: ConfigMap` + "\n" + `  metadata:` + "\n" + `    namespace: metallb-system` + "\n" + `    name: config` + "\n" + `  data:` + "\n" + `    config: |` + "\n" + `      address-pools:` + "\n" + `      - name: default` + "\n" + `        protocol: layer2` + "\n" + `        addresses:` + "\n" + `        - $CLUSTER_CIDR` + "\n" + `EOF` + "\n" + `  kubectl apply -f metallb-config.yaml` + "\n" + `  kubectl wait --for=condition=ready --timeout=5m pod -l app=metallb -n metallb-system` + "\n" + `fi`)
}
func (s *Suite) Test() {}
