// Code generated by gotestmd DO NOT EDIT.
package observability

import (
	"github.com/stretchr/testify/suite"

	"github.com/networkservicemesh/integration-tests/extensions/base"
	"github.com/networkservicemesh/integration-tests/suites/observability/dashboard"
	"github.com/networkservicemesh/integration-tests/suites/observability/jaeger_and_prometheus"
)

type Suite struct {
	base.Suite
	jaeger_and_prometheusSuite jaeger_and_prometheus.Suite
	dashboardSuite             dashboard.Suite
}

func (s *Suite) SetupSuite() {
	parents := []interface{}{&s.Suite}
	for _, p := range parents {
		if v, ok := p.(suite.TestingSuite); ok {
			v.SetT(s.T())
		}
		if v, ok := p.(suite.SetupAllSuite); ok {
			v.SetupSuite()
		}
	}
	s.RunIncludedSuites()
}
func (s *Suite) RunIncludedSuites() {
	s.Run("Dashboard", func() {
		suite.Run(s.T(), &s.dashboardSuite)
	})
	s.Run("Jaeger_and_prometheus", func() {
		suite.Run(s.T(), &s.jaeger_and_prometheusSuite)
	})
}
func (s *Suite) Test() {}
